# Generated by Django 4.1.7 on 2023-03-28 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_producttypeattributesvalues_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductTypeAttributesValues",
            new_name="ProductTypeAttributes",
        ),
    ]
