# Generated by Django 4.1.7 on 2023-03-28 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_rename_producttypeattributesvalues_producttypeattributes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductTypeAttributes",
            new_name="ProductTypeAttribute",
        ),
    ]
