version: "3.8"

services:
  web:
    container_name: web_ecommerce
    depends_on:
      - pgdb
      - redis
      - esearch
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=django-insecure-yis*&11l6rxp8flh5*6xdl#4_%b-!sqao1ra6gz!2ln6=@y%%7
      - NAME=postgres
      - USER=postgres
      - PASSWORD=postgres
      - HOST=pgdb
      - PORT=5432
      - ESEARCH=esearch

    restart: always

  pgdb:
    container_name: pgdb_ecommerce
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: a@a.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  
  
  esearch:
    container_name: search
    image: elasticsearch:7.14.2
    environment:
      - cluster.name=ecommerce-elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    depends_on:
      - pgdb

  redis:
    container_name: redis_ecommerce
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
  celery:
    container_name: celery_ecommerce
    # restart: always
    build:
      context: .
    command: celery -A ecommerce worker -l info
    environment:
      - SECRET_KEY=django-insecure-yis*&11l6rxp8flh5*6xdl#4_%b-!sqao1ra6gz!2ln6=@y%%7
      - NAME=postgres
      - USER=postgres
      - PASSWORD=postgres
      - HOST=pgdb
      - PORT=5432
      - ESEARCH=esearch
      - CELERY_BROKER_URL:"redis://redis:6379/0"
      - CELERY_RESULT_BACKEND:"redis://redis:6379/0"
    depends_on:
      - redis
      - pgdb
    volumes:
      - .:/usr/src/app/
  celery-beat:
    container_name: celery_beat_ecommerce
    restart: always
    build:
      context: .
    command: celery -A ecommerce beat -l info
    depends_on:
      - redis
      - celery
    volumes:
      - .:/usr/src/app/
  flower:
    container_name: flower_ecommerce
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888

